import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { extractIsbnCandidates } from '../ocr';

const runIntegration = process.env.RUN_OCR_INTEGRATION === '1';
const itIf = runIntegration ? it : it.skip;

describe('OCR image fixture (tesseract)', () => {
  itIf('runs Tesseract on PNG fixture and extracts ISBN when recognizable', async () => {
    // Use the E2E fixture (9780306406157) generated by scripts/generate-ocr-fixture.mjs
    const pngPath = join(__dirname, '..', '..', '..', 'e2e', 'fixtures', 'book-spine-isbn.png');
    if (!existsSync(pngPath)) {
      throw new Error(`PNG fixture not found. Run: npm run generate-ocr-fixture`);
    }
    const pngBuffer = readFileSync(pngPath);
    const expectedIsbn = '9780306406157';

    const Tesseract = await import('tesseract.js');
    const { data: { text: ocrText } } = await Tesseract.recognize(pngBuffer, 'eng', {
      tessedit_char_whitelist: '0123456789X',
      tessedit_pageseg_mode: '7',
    });

    // Verify Tesseract integration works: recognize() completes and returns result
    expect(typeof ocrText).toBe('string');

    const candidates = extractIsbnCandidates(ocrText);
    // Best case: extractIsbnCandidates finds the ISBN
    if (candidates.length > 0) {
      expect(candidates).toContain(expectedIsbn);
    }
    // Otherwise: integration still passes (Tesseract ran); recognition varies by env
  }, 20000);
});
